- Necessary imports for the scraping and data collection to work.

In [1]:
import pandas as pd
import requests
pd.set_option('display.max_columns', None)
import time
import numpy as np

You can find the URL within the nba stats website:
- Leaders > Official Leaders: find the stats that you want to work with (per game, totals, regular season, playoffs, etc)
- Inspect the website and go to network (propably must refresh the page)
- In the filters search for leagueLeader: this will be the url that we can manipulate later on

In [4]:
teste = 'https://stats.nba.com/stats/leagueLeaders?LeagueID=00&PerMode=PerGame&Scope=S&Season=2012-13&SeasonType=Regular%20Season&StatCategory=PTS'

In [6]:
r1 = requests.get(url=teste).json()

The table headers will be later used on our dataFrame.

In [7]:
table_headers = r1['resultSet']['headers']

In [9]:
table_headers

['PLAYER_ID',
 'RANK',
 'PLAYER',
 'TEAM_ID',
 'TEAM',
 'GP',
 'MIN',
 'FGM',
 'FGA',
 'FG_PCT',
 'FG3M',
 'FG3A',
 'FG3_PCT',
 'FTM',
 'FTA',
 'FT_PCT',
 'OREB',
 'DREB',
 'REB',
 'AST',
 'STL',
 'BLK',
 'TOV',
 'PTS',
 'EFF']

Adjusting the content of the url in a dataFrame, with results and rows now aligned with the headers.

In [8]:
pd.DataFrame(r1['resultSet']['rowSet'], columns = table_headers)

,PLAYER_ID,RANK,PLAYER,TEAM_ID,TEAM,GP,MIN,FGM,FGA,FG_PCT,FG3M,FG3A,FG3_PCT,FTM,FTA,FT_PCT,OREB,DREB,REB,AST,STL,BLK,TOV,PTS,EFF
0,2546,1,Carmelo Anthony,1610612752,NYK,67,37.0,10.0,22.2,0.449,2.3,6.2,0.379,6.3,7.6,0.830,2.0,4.9,6.9,2.6,0.8,0.5,2.6,28.7,23.2
1,201142,2,Kevin Durant,1610612760,OKC,81,38.5,9.0,17.7,0.510,1.7,4.1,0.416,8.4,9.3,0.905,0.6,7.3,7.9,4.6,1.4,1.3,3.5,28.1,30.4
2,977,3,Kobe Bryant,1610612747,LAL,78,38.6,9.5,20.4,0.463,1.7,5.2,0.324,6.7,8.0,0.839,0.8,4.7,5.6,6.0,1.4,0.3,3.7,27.3,24.6
3,2544,4,LeBron James,1610612748,MIA,76,37.9,10.1,17.8,0.565,1.4,3.3,0.406,5.3,7.0,0.753,1.3,6.8,8.0,7.3,1.7,0.9,3.0,26.8,32.2
4,201935,5,James Harden,1610612745,HOU,78,38.3,7.5,17.1,0.438,2.3,6.2,0.368,8.6,10.2,0.851,0.8,4.1,4.9,5.8,1.8,0.5,3.8,25.9,24.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
178,203143,179,Pablo Prigioni,1610612752,NYK,78,16.2,1.3,2.8,0.455,0.7,1.7,0.396,0.3,0.3,0.880,0.5,1.3,1.8,3.0,0.9,0.0,1.1,3.5,6.6
179,2563,180,Dahntay Jones,1610612737,ATL,78,13.0,1.1,2.8,0.369,0.1,0.6,0.224,1.1,1.4,0.770,0.3,1.0,1.3,0.6,0.3,0.1,0.5,3.4,3.0
180,203110,181,Draymond Green,1610612744,GSW,79,13.4,1.1,3.3,0.327,0.2,0.8,0.209,0.6,0.7,0.818,0.7,2.6,3.3,0.7,0.5,0.3,0.6,2.9,4.7
181,101236,182,Chuck Hayes,1610612758,SAC,74,16.3,1.1,2.6,0.442,0.0,0.0,0.000,0.4,0.6,0.625,1.5,2.5,4.0,1.5,0.4,0.2,0.6,2.7,6.6
182,203105,183,Festus Ezeli,1610612744,GSW,78,14.4,0.9,2.2,0.438,0.0,0.0,0.000,0.6,1.0,0.531,1.8,2.2,4.0,0.3,0.3,0.9,0.8,2.4,5.5

This is the base of our **for loop**, we have now 3 temporary dataframes that will later iterate through the years and the season types (in this case regular or playoffs).

In [10]:
temp_df1 = pd.DataFrame(r1['resultSet']['rowSet'], columns = table_headers)
temp_df2 = pd.DataFrame({'Year':['2012-13' for i in range(len(temp_df1))],
                         'Season_type':['Regular%20Season' for i in range(len(temp_df1))]})
temp_df3 = pd.concat([temp_df2, temp_df1], axis=1)

In [11]:
temp_df3

,Year,Season_type,PLAYER_ID,RANK,PLAYER,TEAM_ID,TEAM,GP,MIN,FGM,FGA,FG_PCT,FG3M,FG3A,FG3_PCT,FTM,FTA,FT_PCT,OREB,DREB,REB,AST,STL,BLK,TOV,PTS,EFF
0,2012-13,Regular%20Season,2546,1,Carmelo Anthony,1610612752,NYK,67,37.0,10.0,22.2,0.449,2.3,6.2,0.379,6.3,7.6,0.830,2.0,4.9,6.9,2.6,0.8,0.5,2.6,28.7,23.2
1,2012-13,Regular%20Season,201142,2,Kevin Durant,1610612760,OKC,81,38.5,9.0,17.7,0.510,1.7,4.1,0.416,8.4,9.3,0.905,0.6,7.3,7.9,4.6,1.4,1.3,3.5,28.1,30.4
2,2012-13,Regular%20Season,977,3,Kobe Bryant,1610612747,LAL,78,38.6,9.5,20.4,0.463,1.7,5.2,0.324,6.7,8.0,0.839,0.8,4.7,5.6,6.0,1.4,0.3,3.7,27.3,24.6
3,2012-13,Regular%20Season,2544,4,LeBron James,1610612748,MIA,76,37.9,10.1,17.8,0.565,1.4,3.3,0.406,5.3,7.0,0.753,1.3,6.8,8.0,7.3,1.7,0.9,3.0,26.8,32.2
4,2012-13,Regular%20Season,201935,5,James Harden,1610612745,HOU,78,38.3,7.5,17.1,0.438,2.3,6.2,0.368,8.6,10.2,0.851,0.8,4.1,4.9,5.8,1.8,0.5,3.8,25.9,24.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
178,2012-13,Regular%20Season,203143,179,Pablo Prigioni,1610612752,NYK,78,16.2,1.3,2.8,0.455,0.7,1.7,0.396,0.3,0.3,0.880,0.5,1.3,1.8,3.0,0.9,0.0,1.1,3.5,6.6
179,2012-13,Regular%20Season,2563,180,Dahntay Jones,1610612737,ATL,78,13.0,1.1,2.8,0.369,0.1,0.6,0.224,1.1,1.4,0.770,0.3,1.0,1.3,0.6,0.3,0.1,0.5,3.4,3.0
180,2012-13,Regular%20Season,203110,181,Draymond Green,1610612744,GSW,79,13.4,1.1,3.3,0.327,0.2,0.8,0.209,0.6,0.7,0.818,0.7,2.6,3.3,0.7,0.5,0.3,0.6,2.9,4.7
181,2012-13,Regular%20Season,101236,182,Chuck Hayes,1610612758,SAC,74,16.3,1.1,2.6,0.442,0.0,0.0,0.000,0.4,0.6,0.625,1.5,2.5,4.0,1.5,0.4,0.2,0.6,2.7,6.6
182,2012-13,Regular%20Season,203105,183,Festus Ezeli,1610612744,GSW,78,14.4,0.9,2.2,0.438,0.0,0.0,0.000,0.6,1.0,0.531,1.8,2.2,4.0,0.3,0.3,0.9,0.8,2.4,5.5

In [12]:
del temp_df1, temp_df2, temp_df3

Adding years and season types to the columns of the dataframe.

In [13]:
df_cols = ['Year', 'Season_type'] + table_headers

In [14]:
pd.DataFrame(columns=df_cols)

Empty DataFrame
Columns: [Year, Season_type, PLAYER_ID, RANK, PLAYER, TEAM_ID, TEAM, GP, MIN, FGM, FGA, FG_PCT, FG3M, FG3A, FG3_PCT, FTM, FTA, FT_PCT, OREB, DREB, REB, AST, STL, BLK, TOV, PTS, EFF]
Index: []

In this part, you can in your click your URL and then find _headers_, then in the lower part, search for your requisition headers, you will need this in the for loop.

In [15]:
headers = {
'Accept':'text/html,application/xhtml+xml,application/xml;q=0.9,image/avif,image/webp,*/*;q=0.8',
'Accept-Encoding':'gzip, deflate, br',
'Accept-Language':'pt-BR,pt;q=0.8,en-US;q=0.5,en;q=0.3',
'Connection':'keep-alive',
'Host':'stats.nba.com',
'Sec-Fetch-Dest':'document',
'Sec-Fetch-Mode':'navigate',
'Sec-Fetch-Site':'none',
'Sec-Fetch-User':'?1',
'TE':'trailers',
'Upgrade-Insecure-Requests':'1',
'User-Agent':'Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:109.0) Gecko/20100101 Firefox/109.0'
}

The for loop works within each year and then each season type, the url will be searched through our string manipulation and the data concatenated in the **df**.
In this case, regular season and playoffs in the latest 10 years were the parameters chosen, per game data. But this can be easily changed depending your demand.

In [17]:
df = pd.DataFrame(columns=df_cols)
season_types = ['Regular%20Season', 'Playoffs']
years = ['2012-13', '2013-14', '2014-15', '2015-16', '2016-17', '2017-18', '2018-19', '2019-20', '2020-21', '2021-22']

begin_loop = time.time()

for y in years:
  for s in season_types:
    api_url = 'https://stats.nba.com/stats/leagueLeaders?LeagueID=00&PerMode=PerGame&Scope=S&Season=' +y+ '&SeasonType=' +s+ '&StatCategory=PTS'
    r = requests.get(url=api_url, headers=headers).json()
    temp_df1 = pd.DataFrame(r['resultSet']['rowSet'], columns = table_headers)
    temp_df2 = pd.DataFrame({'Year':[y for i in range(len(temp_df1))],
                            'Season_type':[s for i in range(len(temp_df1))]})
    temp_df3 = pd.concat([temp_df2, temp_df1], axis=1)
    df = pd.concat([df, temp_df3], axis=0)
    print(f'Finished scraping data for the {y} {s}.')
    lag = np.random.uniform(low=5, high=40)
    print(f'Waiting {round(lag, 1)} seconds.')
    time.sleep(lag)

print(f'Process completed. Total run time {round((time.time()-begin_loop)/60,2)} min.')
df.to_excel('nba_player_data.xlsx', index=False)

Finished scraping data for the 2012-13 Regular%20Season.
Waiting 7.3 seconds.
Finished scraping data for the 2012-13 Playoffs.
Waiting 24.6 seconds.
Finished scraping data for the 2013-14 Regular%20Season.
Waiting 32.3 seconds.
Finished scraping data for the 2013-14 Playoffs.
Waiting 34.4 seconds.
Finished scraping data for the 2014-15 Regular%20Season.
Waiting 31.7 seconds.
Finished scraping data for the 2014-15 Playoffs.
Waiting 12.2 seconds.
Finished scraping data for the 2015-16 Regular%20Season.
Waiting 27.2 seconds.
Finished scraping data for the 2015-16 Playoffs.
Waiting 28.0 seconds.
Finished scraping data for the 2016-17 Regular%20Season.
Waiting 36.4 seconds.
Finished scraping data for the 2016-17 Playoffs.
Waiting 32.3 seconds.
Finished scraping data for the 2017-18 Regular%20Season.
Waiting 25.7 seconds.
Finished scraping data for the 2017-18 Playoffs.
Waiting 11.9 seconds.
Finished scraping data for the 2018-19 Regular%20Season.
Waiting 31.2 seconds.
Finished scraping data for the 2018-19 Playoffs.
Waiting 29.4 seconds.
Finished scraping data for the 2019-20 Regular%20Season.
Waiting 34.0 seconds.
Finished scraping data for the 2019-20 Playoffs.
Waiting 14.7 seconds.
Finished scraping data for the 2020-21 Regular%20Season.
Waiting 5.9 seconds.
Finished scraping data for the 2020-21 Playoffs.
Waiting 31.0 seconds.
Finished scraping data for the 2021-22 Regular%20Season.
Waiting 34.1 seconds.
Finished scraping data for the 2021-22 Playoffs.
Waiting 20.5 seconds.
Process completed. Total run time 8.58 min.

The output is a **xlsx** file that you can work with and proceed with the analysis.